PORT = 8081
HOST = "127.0.0.1"
CONCATENATE_RESPONSES = True
CONCATENATE_RESPONSES_STRING = "\n\n"
DESIRED_TOKENS = 200
CONTINUATION_QUERY = "(continue roleplay from the sentence where you have left, don't forget to use character names)"
MARKUP_FIX = True
COOKIE_NAME = "cookies.json"
USER_MESSAGE_WORKAROUND = True
USER_MESSAGE = "Respond to the text above."
